# Generated by Django 3.2.16 on 2023-10-15 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_rename_comment_comment_post_related'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='post_related',
            new_name='post',
        ),
        migrations.RemoveField(
            model_name='post',
            name='comment',
        ),
    ]
